/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to Explain the concept of Bitwise "AND", "OR" AND "NOT" Operators.
Bitwise AND ( & ) =>
Bitwise OR ( | ) =>
Bitwise NOT ( ^ ) => 
*********************************************************************/

#include <iostream.h>
#include <conio.h>

int main()
{
	clrscr();
	cout << " 1 & 1 is " << (1 & 1) << '\n';
	cout << " 1 | 1 is " << (1 | 1) << '\n';
	cout << " 1 ^ 1 is " << (1 ^ 1) << '\n';
	cout << " 255 << 2 is " << (255 << 2)<< '\n';
	cout << " 255 >> 2 is "<< (255 >> 2) << '\n';
	cout << " ~255 is " << ~(unsigned int)255 << '\n';
	getch();
	return 0;
}

/*********************************************************************
Output :

*********************************************************************/
