/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to find the ASCII Value of any Given Character.
*********************************************************************/

#include <iostream.h>
#include <conio.h>

void main()
{ 
	clrscr();
  	char ch;
  	cout << "\n Enter any character : ";
  	cin >> ch;
  	cout << "\n The ASCII value of " << ch << " is " << int(ch);
	getch();
}

/*********************************************************************
Output :

*********************************************************************/
