/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to explain the concept of short-cut Assignment Operator.
*********************************************************************/

#include <iostream.h>
#include <conio.h>

void main()
{
	clrscr();
	int num = 25;
	num += 10;
	cout << endl << num;
	num -= 5;
	cout << endl << num;
	num *= 2;
	cout << endl << num;
	num /= 3;
	cout << endl << num;
	num %= 3;
	cout << endl << num;
	getch();
}
/*********************************************************************
Output :
 35
 30
 60
 20
 2
*********************************************************************/

