/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to explain the concept of "AUTOMATIC" or "IMPLICIT" type 
conversion.
*********************************************************************/

#include <iostream.h>
#include <conio.h>

void main()
{
	clrscr();
	int a = 10, b = 20;
	float c = 10.50;
	long d = 20L, e;
	
	e = ((a + c) * d) + b;
	cout << " Value of e = " << e;
	getch();

}
/*********************************************************************
Output :

*********************************************************************/
