/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to explain the CASCADING effect of INSERTION "<<" and EXTRACTION
 ">>" Operators.
*********************************************************************/

#include <iostream.h>
#include <conio.h>

void main()
{
	clrscr();
	int num1, num2, sum;
	cout << "\n Enter Two Numbers : ";
	cin >> num1 >> num2;
	sum = num1 + num2;
	cout << "\n " << num1 << " + " << num2
	     << " = " << sum;
	getch();
}
/*********************************************************************
Output :
 Enter Two Numbers : 5 10
 5 + 10 = 15
*********************************************************************/
