/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to Explain Char Data Type AND Char Array.
*********************************************************************/

#include <iostream.h>
#include <conio.h>
#include <stdio.h>

void main()
{
	clrscr();
	char str[10];
	cout << "Enter a String : ";
	gets(str);
	cout << "\n" << str;
	getch();
}
/*********************************************************************
Output :
 Enter a String : BIIT Computer Education
 BIIT Computer Education
*********************************************************************/
