/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to Explain "CHAR-ARRAY" or "STRING".
*********************************************************************/

#include <iostream.h>
#include <conio.h>

void main()
{
	clrscr();
	char c[25];
	cout << " Enter Name : ";
	cin >> c;
	cout << "\n Name = " << c;
	getch();
}

/*********************************************************************
Output :
 Enter Name : BIIT Computer Education.
 Name = BIIT
*********************************************************************/
