/*********************************************************************
		KRISHNA KANT DUBEY
		Sec-2,Hanuman mandir,Bhilai
		( C.G.) 490 006	   Mob.: 9893038337
**********************************************************************
Project No.-
Program to Check the Given Number is Even or Odd.
*********************************************************************/

#include<iostream.h>
#include<conio.h>

void main()
{
	clrscr();
	int a;
	cout << "\n Enter any Number : ";
	cin >> a;
	if(a % 2 == 0)
		cout << "\n Number is EVEN.";
	else
		cout << "\n Number is ODD.";
	getch();
}
/*********************************************************************
Output :
Enter any Number : 354
Number is EVEN.
*********************************************************************/